### ISSUE TITLE
feedback 1

### ISSUE THREAD

**Issue by marcelogdeandrade** [MatheusDMD/Compiler#3]
Release: [1.0.1](https://github.com/MatheusDMD/Compiler/releases/tag/v1.0.1)
Feedback:  O mesmo bug do roteiro 0.
Não trata erro de dois numeros sem operacao (ignora espacos no momento errado)

**Exemplo de entrada:** 11 11 + 2

**Saida esperada:** Erro do parser, nao aceita dois numero seguidos sem operacao
**Saida atual:** 1113 (1111 + 2)

Caso já tenha consertado esse bug na próxima release, apenas comente isso abaixo e eu fecho o issue quando corrigí-lo. Caso contrário, atualize a última release corrigindo o bug.

Também está faltando o diagrama sintático no Github.

Aproveitando, é recomendado que coloque no github as informações para execução do projeto (no caso, versão do python), ele não funciona com python2, apenas python3.

**Comment by marotzke** [comment]
Release: [1.1.2](https://github.com/MatheusDMD/Compiler/releases/tag/v1.1.2) resolve todos os erros apontados

**Comment by marcelogdeandrade** [comment]
Conferido.
